In [24]:
import numpy as np
import pandas as pd

one   = np.array([[1,1,1],[1,1,1]])
zeros = np.array([0,0,0])

In [25]:
# This will not work because the two arrays have different shapes
combined = np.concatenate([one, zeros], axis=0)

ValueError: all the input arrays must have same number of dimensions

In [29]:
#we will need to adjust zeros turning it into a 2D array as follows
#adjust along the X axis because we want to concatenate the rows. 
zeros_2d = np.expand_dims(zeros, axis=0)
zeros_2d 

array([[0, 0, 0]])

In [32]:
#now we can extend the <one> arrays along the  axis (extend rows)
combined = np.concatenate([one, zeros_2d], axis=0)
combined

array([[1, 1, 1],
       [1, 1, 1],
       [0, 0, 0]])

Let deal's with sorting a numpy array: using argsort()
argsort() will return the [indices] that will sort an array

In [39]:
fruit = np.array(['orange', 'banana', 'apple', 'grape', 'cherry'])
sorted_order = np.argsort(fruit)
sorted_fruit = fruit[sorted_order]
sorted_fruit

array(['apple', 'banana', 'cherry', 'grape', 'orange'], dtype='<U6')

In [44]:
# let's sort a 2D ndarray <int_square> by its last column 
int_square = np.array([[5, 2, 8, 3, 4],
                       [2, 8, 6, 2, 5],
                       [1, 6, 2, 7, 7],
                       [0, 7, 7, 4, 5],
                       [5, 7, 1, 1, 2]])

In [50]:
#1. start by selecting just the last column
last_column = int_square[:,4]
#2. get the sorted indices for last column
sorted_order = np.argsort(last_column)
#3. Sort the entire ndarray with the <sorted_order> indices
int_square_sorted = int_square[sorted_order]
int_square_sorted 

array([[5, 7, 1, 1, 2],
       [5, 2, 8, 3, 4],
       [2, 8, 6, 2, 5],
       [0, 7, 7, 4, 5],
       [1, 6, 2, 7, 7]])

Indexing or Selecting using a Boolean Array: boolean selecting/indexing

In [69]:
c = np.array([80.0, 103.4, 96.9, 200.3])
#create boolean array marking all elements > 100
c_bool = c > 100
result = c[c_bool]  #result contains elements greater than 100
result.shape

2

pickup_month = taxi[:,1]

january_bool = pickup_month == 1
january = pickup_month[january_bool]
january_rides = january.shape[0]

february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]

march_bool = pickup_month == 3
march = pickup_month[march_bool]
march_rides = march.shape[0]

Reading data from a file: usng the genfromtxt()
general format is: np.genfromtxt(filename, delimiter=',', skip_header=1)

In [65]:
arr = np.array([2,4,6,8])
arr <= 4


array([ True,  True, False, False])